# Portfolio settings
title: Escape Room SA
email: tig3r86@gmail.com
description: "You have 60 minutes working as a team to discover hidden objects, figure out the clues and unravel mysterious puzzle to escape the room. Bring your friends, family and have a great time."
taglines: "Experience Adelaide's first live puzzle game"
punchline: "60 minutes to escape"


#Menu item list

menu:
- {name: The Game, url: '#game'}
- {name: The Rooms, url: '#room'}
- {name: Faq, url: '#faq'}
- {name: About Us, url: '#about'}
- {name: Book Now, url: '#Book online'}


#-------------------------------
# The game section
#-------------------------------

game-title: "The game"

step1-title: "Work Together in a team"
step1-copy: "This is the copy paragraph accompanying the step1-title"

step2-title: "Beat the clock"
step2-copy: "Solve the puzzles and escape before time runs out. "

step3-title: "Think outside the box"
step3-copy: "Get creative and connect the dots to uncover the hidden clues."

step4-title: "Be the first to escape"
step4-copy: "Make history! Be the first to escape the first live escape game in Adelaide."

#-------------------------------
# The roooms section
#-------------------------------

room-title: "The Rooms"

room1-title: "Killer escape"
room1-copy: "Your team has been tipped off about the location of a serial killer's study, the door is unlocked and you sneak in. You look behind and the door quickly swings shut. You hear a locking noise and from a speaker somewhere you hear: ‘Intruder alert! Intruder alert! Self-destruct sequence has been activated! 1 Hour until self-destruct!’ Find out where the next victim is being held and find a way to escape before the bomb goes off."

room2-title: "No where to go"
room2-copy: "You awake in a basement, it is dark and it is cold. The smell of rot smacks you across the face and sends you reeling. You try to get up and stumble, realising that your hands are tied. There are others. Others locked in the same room as you. Others locked in the room next door. You have no idea how you got here but you do know one thing. This isn't a safe place. Work together as a team to escape before the person who put you here returns."

#-------------------------------
# FAQ section
#-------------------------------

faq-title: "Frequently Asked Questions"

faq:
- question: "I dont have a team of 6, can I still play?"
  answer: "Of course you can! But we do recommend 4 to 6 players, as our puzzles have been designed to be quite challenging. Besides, we charge a fixed price per room, so the more people the cheaper!"

- question: "Am I really locked inside the room?"
  answer: "The front door that you enter from will always be unlocked. This is because if anyone feels uncomfortable during the session, they always have the option to opt out. Unfortunately, the person that comes out cannot enter the room again and will not count as a success escape. Others in the room can still continue on with their mission."

- question: "Will there be anyone scaring us?"
  answer: "Don’t worry! There will be no one popping out from anywhere to scare you."



#-------------------------------
# About Section
#-------------------------------

about-title: "About us"

about-sub-title1: "Who we are"
about-copy1: "Escape Room Sa is one of Adelaide's first independent live escape room venue. Founded by two mates, Anton and Kevin. We are big fans of escape games and have played heaps of venues all around the world in our travel. We were bummed out that our home town awesome Radelaide doesn't have a single escape game venue. So we decided to create one."

about-sub-title1: "Our vision"
about-copy2: "We want to create a fun memorable live escape game experience for everyone. Our aim for every player of the game is to feel the rush of escaping in a safe environment while having a lot of fun as well."

#-------------------------------
# Contact Section
#-------------------------------


#-------------------------------
# SEO Section
#-------------------------------

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'


#-------------------------------
# About Section

# Change the default background image, avatar and blurb
bg-img: hero.jpg
avatar: travitar.jpg

blurb: >
  **Kevin specialises in making things** for human people. Most of the things he makes are [digital interfaces](http://google.com), but he also puts efforts into planning his next [travel adventure](#).
# this is the original html mark up make sure to take the greater sign '>' above out when not using markdown.
# <p><strong>Kevin specialises in making things</strong> for human people. Most of the things he makes are <a href="#">digital interfaces</a>, but he also puts efforts into planning his next <a href="#">travel adventure</a>.</p>

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crisp Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg', name: 'Scott Summers', title: 'Director of Design, Quebec ltd', quote: '**Lorem ipsum dolor sit amet, consectetur adipisicing elit.** Repellat, at vel exercitationem ullam, illum omnis atque sint perferendis nesciunt nobis, autem animi fuga quia consequatur neque deserunt minus magni modi.', logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg', name: 'Scott Summers', title: 'Director of Design, Quebec ltd', quote: '**Lorem ipsum dolor sit amet, consectetur adipisicing elit.** Repellat, at vel exercitationem ullam, illum omnis atque sint perferendis nesciunt nobis, autem animi fuga quia consequatur neque deserunt minus magni modi.', logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg', name: 'Scott Summers', title: 'Director of Design, Quebec ltd', quote: '**Lorem ipsum dolor sit amet, consectetur adipisicing elit.** Repellat, at vel exercitationem ullam, illum omnis atque sint perferendis nesciunt nobis, autem animi fuga quia consequatur neque deserunt minus magni modi.', logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg', name: 'Scott Summers', title: 'Director of Design, Quebec ltd', quote: '**Lorem ipsum dolor sit amet, consectetur adipisicing elit.** Repellat, at vel exercitationem ullam, illum omnis atque sint perferendis nesciunt nobis, autem animi fuga quia consequatur neque deserunt minus magni modi.', logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com'}
- {icon: 'facebook', link: 'http://facebook.com'}
- {icon: 'pinterest', link: 'http://pinterest.com'}
- {icon: 'instagram', link: 'http://instagram.com'}
- {icon: 'youtube', link: 'http://youtube.com'}

# can be: 'twitter' / 'facebook' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'vine'

